/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "../JuceLibraryCode/JuceHeader.h"
#include "BeatCounterAudioProcessor.h"
#include "MainEditorView.h"

//==============================================================================
class BeatCounterAppApplication  : public JUCEApplication
{
public:
    //==============================================================================
    BeatCounterAppApplication() {}

    const String getApplicationName()       { return ProjectInfo::projectName; }
    const String getApplicationVersion()    { return ProjectInfo::versionString; }
    bool moreThanOneInstanceAllowed()       { return false; }

    //==============================================================================
    void initialise (const String& commandLine)
    {
        audioProcessor = new BeatCounterAudioProcessor();
    }

    void shutdown()
    {
        audioProcessor->releaseResources();
    }

    //==============================================================================
    void systemRequestedQuit()
    {
        quit();
    }

    #if 0
    void anotherInstanceStarted (const String& commandLine)
    {
    }
    #endif

private:
    ScopedPointer<BeatCounterAudioProcessor> audioProcessor;
    MainEditorView *mainWindow;
};

//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION (BeatCounterAppApplication)
